version: '3.4'

services:
  # 1. Database Service (SQL Server)
  blog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blog-sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123! 
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # 2.  API Service
  blog-api:
    image: blog-api
    container_name: blog-api-container
    build:
      context: .              
      dockerfile: API/Dockerfile
    ports:
      - "7171:8080"           # Port
    depends_on:
      - blog-db               # Depends on the database service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # SQL Connection String Override
      - ConnectionStrings__BlogAuthConnection=Server=blog-db;Database=BlogDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True;
      # [NEW] JWT Key Override via Environment Variable
      - Jwt__Key=This_Is_A_Very_Secret_And_Long_Docker_Password_Please_Do_Not_Share_123!

volumes:
  sqlvolume: